### ISSUE TITLE
Redesign relationships between VideoReleases, AudioTracks, & SubtitleTracks.

### ISSUE THREAD

**Issue by bayes343** [kbeelman/TokuCinema_Old#1]
I'm not sure exactly how you @kbeelman want to handle these relationships.  I was thinking that Audio and Subtitle tracks should be related to the VideoVersionType, but I'm not sure if this falls in line with how you're envisioning things.  If these data sets (audio and subtitle tracks) need to be release specific, we might be able to even through them into the VideoVersion table, since those records are children of the VideoVersionType and the VideoRelease.  See below concept:

![image](https://cloud.githubusercontent.com/assets/12376716/16864880/3ca068e6-4a15-11e6-8f95-1f79c6d68700.png)

**Comment by kbeelman** [comment]
Thanks for putting the ticket in. Since a lot of releases are dual-language, I think I might need to implement SubtitleTrackType and AudioTrackType to allow a VideoVersion or VideoVersionType to have multiple audio & subtitle tracks associated with it. I'll take care of this when I get back. The database just got even larger.

**Comment by bayes343** [comment]
Check out the changes I made to this diagram.  I think you'll like the new layout a lot better than the old crows feet diagram.  I went ahead and drafted out a basic implementation for audio and subtitle track types.  

[TokuCinemaDatabase_CrowsFeet.pdf](https://github.com/kbeelman/TokuCinema/files/367144/TokuCinemaDatabase_CrowsFeet.pdf)

**Comment by bayes343** [comment]
Database has been redesigned to match the attached diagram.  Issue is resolved.

[TokuCinemaDatabase_CrowsFeet.pdf](https://github.com/kbeelman/TokuCinema/files/381066/TokuCinemaDatabase_CrowsFeet.pdf)
